### ISSUE TITLE
[Feature Request] 建立每一个知识点与ppt页数的索引

### ISSUE THREAD

**Issue by Tloops** [Tloops/CS101B_I2CSB#2]
计导A和B都是开卷考试，能够快速找到相应知识点所对应的课件页数很重要。
建议为每一个知识点都建立索引，让使用者能更快找到知识点位置。

**Comment by yiruihe** [comment]
还有一个比较有效的办法是根据名词建立索引，这样查找起来会比翻找知识点快很多。
也就是说，把每一块重要的名词和对应PPT页码整理到一个excel表格中，然后根据名词的字母排序整理出表格的最终版本。

**Comment by Tloops** [comment]
2023年秋季学期已经未查询到此课，应该已经没有必要再做这个了，故close
