### ISSUE TITLE
[Feature Request] 使用渲染出来的数学符号便于阅读和理解

### ISSUE THREAD

**Issue by yiruihe** [Tloops/CS101B_I2CSB#3]
总结里面夹杂着不少形如 $\Sigma$ （而不是 <img src="https://latex.codecogs.com/svg.image?\Sigma" title="\Sigma" /> ）这样没有渲染出来的公式或者数学符号，我感觉对于正在学计算机导论的同学不是很友好qaq。
【推荐两个可能有用的小网站：https://latex.codecogs.com 和 http://www.sciweavers.org/free-online-latex-equation-editor】

**Comment by Tloops** [comment]
555github识别不了就很难受，这次我会先在本地使用Typora转pdf的，寒假着手改一下

**Comment by yiruihe** [comment]
嗷好的，聂老师辛苦了！～2333

**Comment by Tloops** [comment]
已经完成所有公式的修正，再次感谢~现在我将关闭本issue
