### ISSUE TITLE
关于Editor是否为System  Software的问题

### ISSUE THREAD

**Issue by OctCarp** [Tloops/CS101B_I2CSB#6]
Lesson 11中对System Software一段中这样举例

`
例子：汇编器、编译器、翻译器、操作系统、Editors、linkers、debuggers、storage-media formaters、network software……
`

但是我在网络上没有找到准确说明Editor是系统软件的定义，关于此的问答倾向于将Editor视作应用软件。向刘YP老师请教后老师说“text editor，office这种文本/文档编辑软件，是应用软件”

请问仓库中提到的"Editor"是其他更深层的相关定义吗，它是属于系统软件还是应用软件呢？

**Comment by Tloops** [comment]
这是程老师第六节课课件（21年秋季版）96页最后一点提到的。不过我也查了一下，按照我的理解Text Editor等确实应该是应用软件。我猜测或许课件的意思是支持editor的一些底层接口，如提供修改文件服务的接口等等。
